name: Bill Schneider
description: where I write about software engineering
meta_description: "Bill Schneider's blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://wrschneider.github.io'
google_analytics: 'UA-64845005-1'

# Details for the RSS feed generator
url:            'http://wrschneider.github.io'
author:         'Bill Schneider'
